import React from "react";

const market_products = [
  {
    type: "Demand",
    product_name: "Tomato",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 100000,
    product_price: 20,
    city_name: "Prayagraj",
    state_name: "Uttar Pradesh",
    post_by: "Anjul",
    post_date: "10-07-2024",
    categorie: "Tomato",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Potato",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 100000,
    product_price: 20,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Narayan",
    post_date: "10-07-2024",
    categorie: "Potato",
    status: "Pending",
  },
  {
    type: "Supply",
    product_name: "Wheat",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 100000,
    product_price: 20,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Narayan",
    post_date: "10-07-2024",
    categorie: "Potato",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Rice",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 150000,
    product_price: 30,
    city_name: "Lucknow",
    state_name: "Uttar Pradesh",
    post_by: "Sunita Rani",
    post_date: "11-07-2024",
    categorie: "Rice",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Barley",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 80000,
    product_price: 25,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Rajesh Kumar",
    post_date: "12-07-2024",
    categorie: "Barley",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Corn",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 120000,
    product_price: 22,
    city_name: "Varanasi",
    state_name: "Uttar Pradesh",
    post_by: "Amit Singh",
    post_date: "13-07-2024",
    categorie: "Corn",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Oats",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 70000,
    product_price: 28,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Neha Sharma",
    post_date: "14-07-2024",
    categorie: "Oats",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Soybean",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 60000,
    product_price: 33,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Priti Patel",
    post_date: "15-07-2024",
    categorie: "Soybean",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Millet",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 90000,
    product_price: 18,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Kumar",
    post_date: "16-07-2024",
    categorie: "Millet",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Sorghum",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 80000,
    product_price: 25,
    city_name: "Prayagraj",
    state_name: "Uttar Pradesh",
    post_by: "Suman Yadav",
    post_date: "17-07-2024",
    categorie: "Sorghum",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Rye",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 75000,
    product_price: 35,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Gaurav Verma",
    post_date: "18-07-2024",
    categorie: "Rye",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Chickpeas",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 70000,
    product_price: 40,
    city_name: "Lucknow",
    state_name: "Uttar Pradesh",
    post_by: "Kiran Yadav",
    post_date: "19-07-2024",
    categorie: "Chickpeas",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Peas",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 60000,
    product_price: 22,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Sharma",
    post_date: "20-07-2024",
    categorie: "Peas",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Lentils",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 80000,
    product_price: 30,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Sandeep Kumar",
    post_date: "21-07-2024",
    categorie: "Lentils",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Beans",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 85000,
    product_price: 27,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Anil Kumar",
    post_date: "22-07-2024",
    categorie: "Beans",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Garlic",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 90000,
    product_price: 50,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Rita Devi",
    post_date: "23-07-2024",
    categorie: "Garlic",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Onions",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 65000,
    product_price: 20,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Amit Yadav",
    post_date: "24-07-2024",
    categorie: "Onions",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Ginger",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 55000,
    product_price: 35,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Manish Sharma",
    post_date: "25-07-2024",
    categorie: "Ginger",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Turmeric",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 70000,
    product_price: 45,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Sanjay Gupta",
    post_date: "26-07-2024",
    categorie: "Turmeric",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Coriander",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 65000,
    product_price: 25,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Pooja Sharma",
    post_date: "27-07-2024",
    categorie: "Coriander",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Pepper",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 70000,
    product_price: 38,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Kumar",
    post_date: "28-07-2024",
    categorie: "Pepper",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Cardamom",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 50000,
    product_price: 60,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Kavita Sharma",
    post_date: "29-07-2024",
    categorie: "Cardamom",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Cloves",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 80000,
    product_price: 55,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Kumar",
    post_date: "30-07-2024",
    categorie: "Cloves",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Rose",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 40000,
    product_price: 70,
    city_name: "Prayagraj",
    state_name: "Uttar Pradesh",
    post_by: "Ankit Singh",
    post_date: "31-07-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Lily",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 50000,
    product_price: 60,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Suman Yadav",
    post_date: "01-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Sunflower",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 35000,
    product_price: 30,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Deepika Sharma",
    post_date: "02-08-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Tulip",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 40000,
    product_price: 45,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Rajesh Sharma",
    post_date: "03-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Daisy",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 50000,
    product_price: 20,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Pooja Yadav",
    post_date: "04-08-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Orchid",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 35000,
    product_price: 65,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Amit Kumar",
    post_date: "05-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Lily",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 30000,
    product_price: 55,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Yadav",
    post_date: "06-08-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Jasmine",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 40000,
    product_price: 50,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Patel",
    post_date: "07-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Chrysanthemum",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 20000,
    product_price: 80,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Sandeep Yadav",
    post_date: "08-08-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Marigold",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 25000,
    product_price: 70,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Sunil Kumar",
    post_date: "09-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Poppy",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 15000,
    product_price: 90,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Vijay Sharma",
    post_date: "10-08-2024",
    categorie: "Flower",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Lotus",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 18000,
    product_price: 75,
    city_name: "Prayagraj",
    state_name: "Uttar Pradesh",
    post_by: "Ankit Kumar",
    post_date: "11-08-2024",
    categorie: "Flower",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Aloe Vera",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 20000,
    product_price: 45,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Priya Yadav",
    post_date: "12-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Mint",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 25000,
    product_price: 25,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Amit Verma",
    post_date: "13-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Basil",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 15000,
    product_price: 30,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Pooja Kumar",
    post_date: "14-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Rosemary",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 10000,
    product_price: 60,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Sandeep Kumar",
    post_date: "15-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Thyme",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 12000,
    product_price: 55,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Kavita Sharma",
    post_date: "16-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Lavender",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 15000,
    product_price: 70,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Suman Verma",
    post_date: "17-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Eucalyptus",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 20000,
    product_price: 40,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Verma",
    post_date: "18-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Chamomile",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 18000,
    product_price: 65,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Sandeep Yadav",
    post_date: "19-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Marjoram",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 22000,
    product_price: 50,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Anil Yadav",
    post_date: "20-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Cilantro",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 14000,
    product_price: 35,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Kavita Kumar",
    post_date: "21-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Dill",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 12000,
    product_price: 45,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Ravi Kumar",
    post_date: "22-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Ginseng",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 20000,
    product_price: 90,
    city_name: "Jhansi",
    state_name: "Uttar Pradesh",
    post_by: "Suman Kumar",
    post_date: "23-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Ginger Root",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 30000,
    product_price: 65,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Pooja Yadav",
    post_date: "24-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Lavender Oil",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 10000,
    product_price: 150,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Anil Kumar",
    post_date: "25-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Mint Leaves",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 20000,
    product_price: 40,
    city_name: "Bareilly",
    state_name: "Uttar Pradesh",
    post_by: "Rajesh Kumar",
    post_date: "26-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Aloe Vera Gel",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 15000,
    product_price: 120,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Sandeep Kumar",
    post_date: "27-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Ginger Powder",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 30000,
    product_price: 55,
    city_name: "Noida",
    state_name: "Uttar Pradesh",
    post_by: "Ankit Kumar",
    post_date: "28-08-2024",
    categorie: "Herb",
    status: "Complete",
  },
  {
    type: "Supply",
    product_name: "Herbal Tea",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 15000,
    product_price: 90,
    city_name: "Kanpur",
    state_name: "Uttar Pradesh",
    post_by: "Rajesh Kumar",
    post_date: "29-08-2024",
    categorie: "Herb",
    status: "Pending",
  },
  {
    type: "Demand",
    product_name: "Dandelion",
    product_img: "https://images.pexels.com/photos/54084/wheat-grain-agriculture-seed-54084.jpeg?cs=srgb&dl=pexels-pixabay-54084.jpg&fm=jpg",
    avaliable_stock: 25000,
    product_price: 60,
    city_name: "Agra",
    state_name: "Uttar Pradesh",
    post_by: "Suman Yadav",
    post_date: "30-08-2024",
    categorie: "Herb",
    status: "Complete",
  }
]

const Market_Place_Card = () => {
  return (
    <>
      {market_products.map((market_product, index) => (
        <div
          key={index}
          className="h-[auto] w-[100%] flex justify-center items-center py-4"
        >
          <div className="h-[auto] w-[100%] bg-gray-100 flex justify-center items-center px-4 py-4 rounded-[15px]">
            <div>
              <img
                src={market_product.product_img}
                alt=""
                className="w-[500px] h-[200px] rounded-[10px]"
              />
            </div>
            <div className="w-[100%] h-[100%] py-1 px-7">
              <div className="flex justify-evenly items-start flex-col gap-1">
                <div className=" flex justify-center item-center gap-3">
                  <div className="text-3xl font-semibold text-black">{market_product.product_name}</div>
                  <div className="flex justify-center item-center border border-gray-500 px-5 text-gray-500 rounded-[50px] h-[100%] mt-2 font-semibold">{market_product.type}</div>
                </div>
                <div className="font-semibold text-black">
                  Available Stock Weight (Kg) :{" "}
                  <span className="font-semibold text-gray-500">
                    {market_product.avaliable_stock}{" "}
                  </span>
                </div>
                <div className="flex justify-center items-center gap-3">
                  <div className="font-semibold text-black">
                    Price :{" "}
                    <span className="font-semibold text-gray-500">
                      Rs {market_product.product_price} (Per Kg)
                    </span>{" "}
                  </div>
                  <div>Rating</div>
                </div>
                <div className="flex justify-center items-center gap-4">
                  <div className="font-semibold text-black">
                    City:{" "}
                    <span className="font-semibold text-gray-500">
                      {market_product.city_name}
                    </span>
                  </div>
                  <div className="font-semibold text-black">
                    State:{" "}
                    <span className="font-semibold text-gray-500">
                      {market_product.state_name}
                    </span>
                  </div>
                </div>
                <div className="flex justify-center item-center gap-3">
                  <button className="py-[7px] px-[15px] bg-green-500 font-semibold text-white rounded-[50px]">
                    Buy Now
                  </button>
                  <button className="py-[7px] px-[15px] bg-green-500 font-semibold text-white rounded-[50px]">
                    View Detail
                  </button>
                </div>
                <div className="font-semibold text-black">
                  Posted by:{" "}
                  <span className="font-semibold text-gray-500">
                    {market_product.post_by}
                  </span>{" "}
                  on{" "}
                  <span className="font-semibold text-gray-500">
                    {market_product.post_date}
                  </span>{" "}
                  in{" "}
                  <span className="font-semibold text-gray-500">
                    {market_product.categorie}
                  </span>{" "}
                  <span className="font-semibold text-gray-500">
                    {market_product.status}
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>
      ))}
    </>
  );
};

export default Market_Place_Card;
